"""CreatedAt added to the task model

Revision ID: 1c32de36cd3d
Revises: db98cdd86da1
Create Date: 2024-08-12 14:45:36.060421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c32de36cd3d'
down_revision = 'db98cdd86da1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
